### ISSUE TITLE
Steam games not detected

### ISSUE THREAD

**Issue by Mohal59** [Drommedhar/DlssUpdater#11]
Hi, I don't know why, while GOG, Epic and Gamepass games are well detected, Steam games are not detected at all.

There's the right path for Steam in the settings.

I've got Steam games on several SSD, maybe that's why?

**Comment by Drommedhar** [comment]
As I wrote here (https://github.com/Drommedhar/DlssUpdater/issues/12) this should work.
At least it does on my side and on a friends PC.

Might need to add even more logging to the Steam parser.
Can you attach your logfile, so I can see whats in it?

**Comment by Mohal59** [comment]
ok here it is
[AppLog.2024-10-06.txt](https://github.com/user-attachments/files/17269507/AppLog.2024-10-06.txt)

**Comment by Drommedhar** [comment]
Okay thats odd. We might be onto something here.

Could you pleasxe check if the following file is present: E:\Steam
\steamapps\libraryfolders.vdf
If it is, could you maybe provide it? There might be something different to it then mine. I ask because the log shows its not even trying to read any steam game. I most definately need to increase Logging for steam tomorrow.

**Comment by Mohal59** [comment]
There is a libraryfolders.vdf in E:\Steam\steamapps\

[libraryfolders.zip](https://github.com/user-attachments/files/17269539/libraryfolders.zip)

**Comment by Drommedhar** [comment]
Thanks.
I actually found a bug because of that.

One library path did not have Apps installed and I incorrectly ignored this entry, which in turn completly stopped parsing games from steam.

This one will be fixed in the next version.

**Comment by Drommedhar** [comment]
I just pushed an Update (2.0.2.0) which hopefully fixes your issue.
If not I at least have more data on what exactly might have failed.

**Comment by Mohal59** [comment]
Good work, with 2.0.2.0 Steam games are detected .
