### ISSUE TITLE
Enhancement Proposal – Add Option to Detect Steam Games Across Multiple Hard Drives

### ISSUE THREAD

**Issue by Hitman47** [Drommedhar/DlssUpdater#12]
Current Issue: As an avid gamer and frequent user of Steam, I have encountered a limitation within DLSSUpdater. Currently, the software only detects Steam games installed on the primary hard drive. However, many users, including myself, often distribute their game library across multiple hard drives to manage storage space and optimize performance. This limitation results in DLSSUpdater not recognizing games stored on secondary drives, leading to incomplete management and oversight of my game library.

Proposed Improvement: I would like to propose the addition of a feature that allows DLSSUpdater to detect and manage Steam games installed on multiple hard drives. Specifically, an option within the settings where users can specify additional directories or drives for the software to scan for Steam installations and associated game files would be highly beneficial.

Benefits: Implementing this feature would offer several advantages:

Comprehensive Game Management: Users would have a complete overview of their entire Steam library, regardless of where the games are installed.
Enhanced User Experience: Streamlining the detection process across multiple drives would save users time and reduce the need for manual configuration.
Increased Flexibility: Allowing multiple drive detections would cater to advanced users who utilize various storage solutions, thereby broadening DLSSUpdater’s appeal.
Optimized Storage Utilization: Users can better manage their storage resources by easily identifying and organizing games spread across different drives.

Thank you very much for your time and for continuing to develop such a valuable tool.

**Comment by Drommedhar** [comment]
It should detect them on all hard drives, as it does for me.
The path you see in settings is only the base Steam install diectory. From there I parse several files that also give me the different Steam Library locations.
Sou in theory you should get all your games, assuming they have any DLSS implementation.

**Comment by Drommedhar** [comment]
@Hitman47:
Could you also provide me with your logfiles, so I can check them?

**Comment by Hitman47** [comment]
[AppLog.2024-10-06.txt](https://github.com/user-attachments/files/17269517/AppLog.2024-10-06.txt)

Sure, here it is.
Weidly the software won't see my steam library if I try to change the steam location manually...
Now it's not displaying any game at all.
I have games on 4 differents disks, but the soft don't see all of them (even on the same disk). Apparently only Epic don't have any problem.
Ubisoft won't even display any game at all, and I don't have any problem with them

**Comment by Drommedhar** [comment]
The Installation path needs to point to the actual steam installation, not a library folder.
It should not be needed to actually switch the folder.

**Comment by Hitman47** [comment]
yeah that's what i did initially, but since it doesn't seem to work I tried.
With that configuration the software only see a few games (compatible with DLSS, obviously)

**Comment by Drommedhar** [comment]
Could you please clear your settings and log folder (so its a fresh start) and start the software again.
Please send me this logfile again and (if possible) also your "libraryfolder.vdf" inside SteamInstallDirectory\steamapps\

I found a bug with parsing this one in a another bug.

Also you could try starting Dlss Updater as Admin, so we can make sure it's not something related to rights.

**Comment by Drommedhar** [comment]
As for "Ubisoft won't even display any game at all, and I don't have any problem with them":
I'm currently guessing that they might be stored in a different Registry. I'm currently only trying to find the entries in "LocalMachine32". Maybe they are in either User32 or the 64bit Variant. I will increase the check for all registry keys to all 4 possible paths.

**Comment by Drommedhar** [comment]
I just pushed an Update (2.0.2.0) which hopefully fixes your issues.
If not I at least have more data on what exactly might have failed.

**Comment by Hitman47** [comment]
I just tested, and all the problems are fixed now !
Thank you, it's perfect.
