### ISSUE TITLE
Only one new game can be added manually. 

### ISSUE THREAD

**Issue by NChag** [Drommedhar/DlssUpdater#15]
Only one new game can be added manually. See Steps to reproduce. 
Thank you for the awesome app! 

When adding a second game manually, the info. of the previously added game is pre-filled in the form. When you change/update the form with 2nd game's info. it then creates a second entry but also overwrites the info. of the 1st game. Thus you can only add one game manually. Not sure if these was fixed in the update 2 days ago. If so, please disregard. 

Completion Criteria: allow for many individual games to be added at any given point.

**Comment by Drommedhar** [comment]
I can say I found the bug and fixed another UI bug with it too too :D
It will be in 2.0.4.0. Please check if the bug persists after this version is released.

**Comment by Drommedhar** [comment]
Fixed in 2.0.4.0
