### ISSUE TITLE
Games Duplicated

### ISSUE THREAD

**Issue by WeirdScienceX** [Drommedhar/DlssUpdater#18]
Games are duplicated in the list.
 - DlssUpdater version: Version 2.0.4.0

![image](https://github.com/user-attachments/assets/d8d04805-f350-429a-a228-1d11602bd2bc)

**Comment by Drommedhar** [comment]
Could you maybe attach your LogFile (Log Folder next to the executable).
I had someone else report that this has happened before but I can't reproduce the issue on my side. Maybe I see something.

The Games are actually checked by the Install path, so no same game is added twice, maybe I made a mistake there. But I would need to know the paths, which I should see in the logfile.

**Comment by WeirdScienceX** [comment]
Here you go.  Thanks. 
[logs.zip](https://github.com/user-attachments/files/17367234/logs.zip)

**Comment by Drommedhar** [comment]
The newest version 2.0.5.0 should hopefully fix this issue. Could you check that? (Sorry for the delay, real life took over :D )

**Comment by WeirdScienceX** [comment]
No worries, that seems to have fixed the issue.  Thanks for the fix :)
