### ISSUE TITLE
App crash on startup after uninstalling a game but its folder is still configured within the app

### ISSUE THREAD

**Issue by P40L0X** [Drommedhar/DlssUpdater#19]
**Describe the bug**
When a game is uninstalled (including its main folder) but that folder is left configured in DlssUpdater, every time the app is opened next it crashes on startup.  The only way to solve it is to delete its games.json file under settings folder, but then we need to re-enter all the game's folder manually...

**To Reproduce**
1. Add a game folder to DlssUpdater
2. Close DlssUpdater
3. Uninstall that game and its folder
4. Try to open DlssUpdater again -> **and it will crash every time**

**Expected behavior**
Opening DlssUpdater after a game uninstall shouldn't crash it, but should just show that folder no longer exist with a warning or similar

**Desktop**
 - DlssUpdater version: Version 2.0.4.0

**Additional context**
Attaching my log
[AppLog.2024-10-15.txt](https://github.com/user-attachments/files/17385266/AppLog.2024-10-15.txt)

**Comment by Drommedhar** [comment]
Will look into it.

**Comment by Drommedhar** [comment]
@P40L0X The newest release "2.0.5.2" should hopefully fix your issue. Could you check that?

**Comment by P40L0X** [comment]
> @P40L0X The newest release "2.0.5.2" should hopefully fix your issue. Could you check that?

I confirm the issue is now fixed. 
Thanks!
