### ISSUE TITLE
 New DLSS ray reconstruction dll file in Star wars Outlaws

### ISSUE THREAD

**Issue by Mohal59** [Drommedhar/DlssUpdater#28]
I noticed that in the folder of Star Wars Outlaws game there is a new version of the DLL file for the Ray Reconstruction (nvngx_dlssd.dll 3.7.20). More recent than the one given on the TechPowerUp website or in your application (3.7.10).

I tried to warn TechPowerUp by e-mail but without success.

I enclose the file just in case.
[nvngx_dlssd.zip](https://github.com/user-attachments/files/17880041/nvngx_dlssd.zip)

**Comment by Drommedhar** [comment]
As I'm just using the dlls from TechPowerUp, there is not much I can do here.
I guess its displaying that an update is available?

**Comment by Mohal59** [comment]
No, it's good, in your application it only displays the version number without wanting to update it. In fact, it was when I saw that Cyberpunk 2077 didn't have the same version number than Star Wars Outlaws that I noticed this. These are the only two games with Ray Reconstruction that I own.
