### ISSUE TITLE
"Update Available" badge appears even if there are no new DLSS files actually available

### ISSUE THREAD

**Issue by P40L0X** [Drommedhar/DlssUpdater#5]
**Describe the bug**
Opening the app there is a yellow badge on top of all games saying an update is available for current installed DLSS .dlss...but actually those are already latest.

**To Reproduce**
1. Just Open the app and go to Games section
2. When also going to DLSS section to see which version of DLSS are available, the latest DLSS Upscaler is already installed while Frame Generation and Ray Reconstruction pages are empty

**Expected behavior**
DLSS section should have/read the latest DLSS .dlss installed both for DLSS Upscaler, Frame Gen and Ray Reconstruction and considering the latest versions are already installed/downloaded, the "Update Available" notification should not appear

**Screenshots**
![updateavaiilable](https://github.com/user-attachments/assets/07e9bae4-da76-44b2-8317-d993b1b53c28)

![nodlss](https://github.com/user-attachments/assets/762c32a4-61ab-4458-89db-59f196ad5ae3)

**Desktop (please complete the following information):**

- DlssUpdater version: Version 1.0.2.0 (opened as an Administrator)

CASE: Cooler Master MasterBox NR200P MAX (ITX) + AIO 280mm + PSU SFX Gold 80-PLUS 850W
CPU: AMD Ryzen 7800X3D
GPU: PNY RTX 4080 XLR8 OC
RAM: Corsair Vengeance RGB 32GB (16x2) DDR5 6000Mhz CL30 for AMD (with EXPO)
SSD: WD SN850X 2TB NVMe (7300 MB/s)
Motherboard: ROG Strix B650E-I
Extra fans: 2x ARCTIC P12 Slim
Thermal Paste: Noctua NT-H2 3.5g AM5 Edition
OS: Windows 11 24H2 (Build 26100.1742 - No Insider)

**Additional context**
I'm also attaching my log file when this happened.

[AppLog.2024-09-26.txt](https://github.com/user-attachments/files/17150889/AppLog.2024-09-26.txt)

**Comment by Drommedhar** [comment]
There is something pretty strange happening on your side.
The 3 dlss tabs should never be absolutly empty. There should always be entries there.

**Comment by P40L0X** [comment]
> There is something pretty strange happening on your side. The 3 dlss tabs should never be absolutly empty. There should always be entries there.

I tried to delete the entire folder and re-download/install latest 1.0.2.0 and now the "Update available" is gone and DLSS are showing again.
Don't know what happened (and if it may happen again) tho...

**Comment by P40L0X** [comment]
> We need to keep an eye on this. Maybe there is a bug with the updater. Please tell me when something strange happens again.

Sure, I'll let you know if with the next auto update things get messy again.

Thanks
